### PR TITLE
Fixed update state on unmounted component error.

### PR DESCRIPTION
**Pull request by ErikParso**
* Can't perform a React state update on an unmounted component error fix
* Added unmount AnimatedNumber component button in demo

### CODE REVIEW

**Comment by jfabellera** [comment]
@Leocardoso94 any chance of this getting merged?

**Comment by ErikParso** [comment]
@jfabellera hi, not sure maybe in future. Try sa-animated-number-react while new version IS available. Its forked from this repo with fix

**Comment by jfabellera** [comment]
@ErikParso thanks! It's working great

**Comment by ZilvinasKucinskas** [comment]
Waiting for the new release as well.  Thanks for `sa-animated-number-react` workaround.

**Comment by elyobo** [comment]
Thanks for your workaround @ErikParso.

I think my changes in https://github.com/Leocardoso94/animated-number-react/pull/28 are probably a better approach to resolving this, as it prevents the animation from running at all after unmount (which prevents the modification of state) instead of simply preventing the ongoing animation from attempting to modify state.

The additional changes to `package.json` and the addition of the GH action config files should ideally be kept in another branch in your own repo rather than in the PR, as the maintainer won't want them merged into this repo.

**Comment by ErikParso** [comment]
@elyobo it was just Quick fix to get rid of the error. After a long time not reviewing this PR by owner i decided to create own release because we needed fix in production. Anyway yours solution seems to be better and ill abandon this one. Hope it was tested as well. 

This package seems to be dead and I personally suggest to find another one.

**Comment by elyobo** [comment]
Thanks @ErikParso - are you accepting PRs on your fork? I came here because my colleague started using yours and wanted to keep an eye on when the fix was merged upstream :)

**Comment by ErikParso** [comment]
@elyobo yes feel free to create PR in fork and ill deploy it

**Comment by elyobo** [comment]
Thanks, I'll get one up this evening.

**Comment by elyobo** [comment]
Added https://github.com/ErikParso/animated-number-react/pull/1

**Pull request closed without merging**
